name: arriba
channels:
  - conda-forge
  - bioconda
  - main
  - defaults
  - r
  - anaconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - arriba=2.3.0
  - binutils_impl_linux-64=2.36.1
  - binutils_linux-64=2.36
  - bioconductor-biobase=2.50.0
  - bioconductor-biocgenerics=0.36.0
  - bioconductor-biocparallel=1.24.0
  - bioconductor-biostrings=2.58.0
  - bioconductor-delayedarray=0.16.0
  - bioconductor-genomeinfodb=1.26.0
  - bioconductor-genomeinfodbdata=1.2.4
  - bioconductor-genomicalignments=1.26.0
  - bioconductor-genomicranges=1.42.0
  - bioconductor-iranges=2.24.0
  - bioconductor-matrixgenerics=1.2.0
  - bioconductor-rhtslib=1.22.0
  - bioconductor-rsamtools=2.6.0
  - bioconductor-s4vectors=0.28.0
  - bioconductor-summarizedexperiment=1.20.0
  - bioconductor-xvector=0.30.0
  - bioconductor-zlibbioc=1.36.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2022.6.15
  - cairo=1.16.0
  - certifi=2022.6.15
  - curl=7.82.0
  - expat=2.4.8
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gcc_impl_linux-64=9.4.0
  - gcc_linux-64=9.4.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=9.4.0
  - gfortran_linux-64=9.4.0
  - graphite2=1.3.13
  - gsl=2.6
  - gxx_impl_linux-64=9.4.0
  - gxx_linux-64=9.4.0
  - harfbuzz=2.9.0
  - htslib=1.15.1
  - icu=68.2
  - jpeg=9d
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - krb5=1.19.3
  - ld_impl_linux-64=2.36.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.82.0
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-devel_linux-64=9.4.0
  - libgcc-ng=12.1.0
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libglib=2.68.3
  - libgomp=12.1.0
  - libiconv=1.16
  - liblapack=3.8.0
  - libnghttp2=1.46.0
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libsanitizer=9.4.0
  - libssh2=1.9.0
  - libstdcxx-devel_linux-64=9.4.0
  - libstdcxx-ng=12.1.0
  - libtiff=4.2.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.12
  - libzlib=1.2.12
  - lz4-c=1.9.2
  - make=4.3
  - ncurses=6.3
  - openssl=1.1.1q
  - pango=1.48.9
  - pcre=8.44
  - pcre2=10.36
  - pip=20.3.1
  - pixman=0.40.0
  - pthread-stubs=0.4
  - python=3.9.0
  - python_abi=3.9
  - r-base=4.0.5
  - r-bh=1.72.0_3
  - r-bitops=1.0_6
  - r-circlize=0.4.11
  - r-colorspace=2.0_0
  - r-crayon=1.3.4
  - r-formatr=1.7
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-globaloptions=0.1.2
  - r-lambda.r=1.2.4
  - r-lattice=0.20_41
  - r-matrix=1.2_18
  - r-matrixstats=0.57.0
  - r-rcurl=1.98_1.2
  - r-shape=1.4.5
  - r-snow=0.4_3
  - readline=8.1.2
  - samtools=1.15.1
  - sed=4.8
  - setuptools=51.0.0
  - sqlite=3.33.0
  - star=2.7.10a
  - sysroot_linux-64=2.12
  - tk=8.6.10
  - tktable=2.10
  - tzdata=2020d
  - wheel=0.36.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.4.5
