name: arriba
channels:
  - conda-forge
  - bioconda
  - main
  - defaults
  - r
  - anaconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - arriba=2.2.1
  - binutils_impl_linux-64=2.36.1
  - binutils_linux-64=2.36
  - bioconductor-biobase=2.54.0
  - bioconductor-biocgenerics=0.40.0
  - bioconductor-biocparallel=1.28.0
  - bioconductor-biostrings=2.62.0
  - bioconductor-delayedarray=0.20.0
  - bioconductor-genomeinfodb=1.30.0
  - bioconductor-genomeinfodbdata=1.2.7
  - bioconductor-genomicalignments=1.30.0
  - bioconductor-genomicranges=1.46.0
  - bioconductor-iranges=2.28.0
  - bioconductor-matrixgenerics=1.6.0
  - bioconductor-rhtslib=1.26.0
  - bioconductor-rsamtools=2.10.0
  - bioconductor-s4vectors=0.32.0
  - bioconductor-summarizedexperiment=1.24.0
  - bioconductor-xvector=0.34.0
  - bioconductor-zlibbioc=1.40.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cairo=1.16.0
  - curl=7.81.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.94
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gcc_impl_linux-64=9.4.0
  - gcc_linux-64=9.4.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=9.4.0
  - gfortran_linux-64=9.4.0
  - graphite2=1.3.13
  - gsl=2.7
  - gxx_impl_linux-64=9.4.0
  - gxx_linux-64=9.4.0
  - harfbuzz=3.3.1
  - htslib=1.12
  - icu=69.1
  - jbig=2.1
  - jpeg=9e
  - kernel-headers_linux-64=2.6.32
  - krb5=1.19.2
  - ld_impl_linux-64=2.36.1
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.81.0
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-devel_linux-64=9.4.0
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.70.2
  - libgomp=11.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libnghttp2=1.46.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libsanitizer=9.4.0
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=9.4.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxml2=2.9.12
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - make=4.3
  - ncurses=6.2
  - openssl=1.1.1l
  - pango=1.50.3
  - pcre=8.45
  - pcre2=10.37
  - pixman=0.40.0
  - pthread-stubs=0.4
  - r-base=4.1.2
  - r-bh=1.78.0_0
  - r-bitops=1.0_7
  - r-circlize=0.4.13
  - r-colorspace=2.0_2
  - r-crayon=1.4.2
  - r-formatr=1.11
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-globaloptions=0.1.2
  - r-lambda.r=1.2.4
  - r-lattice=0.20_45
  - r-matrix=1.4_0
  - r-matrixstats=0.61.0
  - r-rcurl=1.98_1.5
  - r-shape=1.4.6
  - r-snow=0.4_4
  - readline=8.1
  - samtools=1.12
  - sed=4.8
  - star=2.7.10a
  - sysroot_linux-64=2.12
  - tk=8.6.11
  - tktable=2.10
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.2
