name: bashbone
channels:
  - conda-forge
  - bioconda
  - main
  - defaults
  - r
  - anaconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - autoconf=2.69
  - automake=1.16.5
  - bc=1.07.1
  - bcftools=1.14
  - bedtools=2.30.0
  - binutils_impl_linux-64=2.36.1
  - binutils_linux-64=2.36
  - bioconductor-annotate=1.72.0
  - bioconductor-annotationdbi=1.56.1
  - bioconductor-biobase=2.54.0
  - bioconductor-biocfilecache=2.2.0
  - bioconductor-biocgenerics=0.40.0
  - bioconductor-biocio=1.4.0
  - bioconductor-biocparallel=1.28.0
  - bioconductor-biomart=2.50.0
  - bioconductor-biostrings=2.62.0
  - bioconductor-clusterprofiler=4.2.0
  - bioconductor-delayedarray=0.20.0
  - bioconductor-deseq2=1.34.0
  - bioconductor-dexseq=1.40.0
  - bioconductor-do.db=2.9
  - bioconductor-dose=3.20.0
  - bioconductor-enrichplot=1.14.1
  - bioconductor-fgsea=1.20.0
  - bioconductor-genefilter=1.76.0
  - bioconductor-geneplotter=1.72.0
  - bioconductor-genomeinfodb=1.30.0
  - bioconductor-genomeinfodbdata=1.2.7
  - bioconductor-genomicalignments=1.30.0
  - bioconductor-genomicdatacommons=1.18.0
  - bioconductor-genomicfeatures=1.46.1
  - bioconductor-genomicranges=1.46.0
  - bioconductor-ggtree=3.2.0
  - bioconductor-go.db=3.14.0
  - bioconductor-gosemsim=2.20.0
  - bioconductor-impute=1.68.0
  - bioconductor-iranges=2.28.0
  - bioconductor-keggrest=1.34.0
  - bioconductor-matrixgenerics=1.6.0
  - bioconductor-multiassayexperiment=1.20.0
  - bioconductor-preprocesscore=1.56.0
  - bioconductor-qvalue=2.26.0
  - bioconductor-raggedexperiment=1.18.0
  - bioconductor-rhtslib=1.26.0
  - bioconductor-rsamtools=2.10.0
  - bioconductor-rtracklayer=1.54.0
  - bioconductor-s4vectors=0.32.0
  - bioconductor-summarizedexperiment=1.24.0
  - bioconductor-tcgautils=1.14.0
  - bioconductor-treeio=1.18.0
  - bioconductor-xvector=0.34.0
  - bioconductor-zlibbioc=1.40.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bwidget=1.9.14
  - bz2file=0.98
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - cairo=1.16.0
  - certifi=2021.10.8
  - clustalw=2.1
  - cmake=3.21.3
  - curl=7.81.0
  - cycler=0.11.0
  - datamash=1.7
  - dos2unix=7.4.1
  - entrez-direct=16.2
  - expat=2.4.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.94
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.29.1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gcc_impl_linux-64=9.4.0
  - gcc_linux-64=9.4.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=9.4.0
  - gfortran_linux-64=9.4.0
  - ghostscript=9.54.0
  - giflib=5.2.1
  - glib=2.70.2
  - glib-tools=2.70.2
  - gmp=6.2.1
  - graphite2=1.3.13
  - gsl=2.7
  - gxx_impl_linux-64=9.4.0
  - gxx_linux-64=9.4.0
  - harfbuzz=3.3.1
  - hdf5=1.10.6
  - htseq=1.99.2
  - htslib=1.14
  - icu=69.1
  - java-jdk=8.0.112
  - jbig=2.1
  - jpeg=9e
  - kernel-headers_linux-64=2.6.32
  - khmer=3.0.0a3
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=2.2.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.81.0
  - libdb=6.2.32
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-devel_linux-64=9.4.0
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgit2=1.3.0
  - libglib=2.70.2
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libimagequant=2.17.0
  - liblapack=3.9.0
  - libnghttp2=1.46.0
  - libnsl=2.0.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libsanitizer=9.4.0
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=9.4.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libunistring=0.9.10
  - libuuid=2.32.1
  - libuv=1.43.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxml2=2.9.12
  - libxslt=1.1.33
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - m4=1.4.18
  - make=4.3
  - matplotlib-base=3.5.1
  - munkres=1.1.4
  - mysql-connector-c=6.1.11
  - ncbi-ngs-sdk=2.11.2
  - ncurses=6.2
  - nlopt=2.7.1
  - numpy=1.21.5
  - openjdk=8.0.112
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - ossuuid=1.6.2
  - packaging=21.3
  - paml=4.9
  - pandoc=2.17.1.1
  - pango=1.50.3
  - pbzip2=1.1.13
  - pcre=8.45
  - pcre2=10.37
  - perl=5.32.1
  - perl-algorithm-diff=1.201
  - perl-app-cpanminus=1.7045
  - perl-base=2.23
  - perl-bio-asn1-entrezgene=1.73
  - perl-bio-coordinate=1.007001
  - perl-bio-eutilities=1.75
  - perl-bio-featureio=1.6.905
  - perl-bio-samtools=1.43
  - perl-bio-tools-phylo-paml=1.7.3
  - perl-bio-tools-run-alignment-clustalw=1.7.4
  - perl-bio-tools-run-alignment-tcoffee=1.7.4
  - perl-bioperl=1.7.8
  - perl-bioperl-core=1.7.8
  - perl-bioperl-run=1.007002
  - perl-business-isbn=3.004
  - perl-business-isbn-data=20140910.003
  - perl-capture-tiny=0.48
  - perl-carp=1.50
  - perl-class-data-inheritable=0.08
  - perl-common-sense=3.74
  - perl-compress-raw-zlib=2.101
  - perl-constant=1.33
  - perl-data-dumper=2.173
  - perl-data-stag=0.14
  - perl-db-file=1.855
  - perl-dbi=1.642
  - perl-devel-stacktrace=2.04
  - perl-digest-hmac=1.03
  - perl-digest-md5=2.55
  - perl-encode=3.16
  - perl-encode-locale=1.05
  - perl-exception-class=1.44
  - perl-exporter=5.74
  - perl-exporter-tiny=1.002001
  - perl-extutils-makemaker=7.64
  - perl-file-listing=6.04
  - perl-file-path=2.18
  - perl-file-slurp-tiny=0.004
  - perl-file-sort=1.01
  - perl-file-temp=0.2304
  - perl-getopt-long=2.50
  - perl-graph=0.9704
  - perl-html-parser=3.72
  - perl-html-tagset=3.20
  - perl-http-cookies=6.04
  - perl-http-daemon=6.01
  - perl-http-date=6.02
  - perl-http-message=6.18
  - perl-http-negotiate=6.01
  - perl-io-html=1.001
  - perl-io-socket-ssl=2.066
  - perl-io-string=1.08
  - perl-json=4.02
  - perl-json-xs=2.34
  - perl-libwww-perl=6.39
  - perl-libxml-perl=0.08
  - perl-list-moreutils=0.428
  - perl-list-moreutils-xs=0.428
  - perl-lwp-mediatypes=6.04
  - perl-mime-base64=3.15
  - perl-mldbm=2.05
  - perl-net-http=6.19
  - perl-net-ssleay=1.88
  - perl-ntlm=1.09
  - perl-parent=0.238
  - perl-storable=3.15
  - perl-sub-uplevel=0.2800
  - perl-test-deep=1.128
  - perl-test-differences=0.67
  - perl-test-exception=0.43
  - perl-test-harness=3.42
  - perl-test-most=0.35
  - perl-test-simple=1.302188
  - perl-test-warn=0.36
  - perl-text-csv=2.00
  - perl-text-diff=1.45
  - perl-time-local=1.28
  - perl-tree-dag_node=1.31
  - perl-try-tiny=0.30
  - perl-types-serialiser=1.0
  - perl-uri=1.76
  - perl-url-encode=0.03
  - perl-www-robotrules=6.02
  - perl-xml-dom=1.46
  - perl-xml-dom-xpath=0.14
  - perl-xml-libxml=2.0132
  - perl-xml-libxslt=1.94
  - perl-xml-namespacesupport=1.12
  - perl-xml-parser=2.44_01
  - perl-xml-regexp=0.04
  - perl-xml-sax=1.02
  - perl-xml-sax-base=1.09
  - perl-xml-sax-expat=0.51
  - perl-xml-simple=2.25
  - perl-xml-xpathengine=0.14
  - perl-xsloader=0.24
  - pillow=9.0.1
  - pip=22.0.3
  - pixman=0.40.0
  - pkg-config=0.29.2
  - pthread-stubs=0.4
  - pyparsing=3.0.7
  - pysam=0.17.0
  - python=3.7.12
  - python-dateutil=2.8.2
  - python_abi=3.7
  - r-abind=1.4_5
  - r-acepack=1.4.1
  - r-ape=5.6_1
  - r-aplot=0.1.2
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.4.1
  - r-base=4.1.2
  - r-base64enc=0.1_3
  - r-bh=1.78.0_0
  - r-biocmanager=1.30.16
  - r-bit=4.0.4
  - r-bit64=4.0.5
  - r-bitops=1.0_7
  - r-blob=1.2.2
  - r-boot=1.3_28
  - r-brew=1.0_7
  - r-brio=1.1.3
  - r-broom=0.7.12
  - r-bslib=0.3.1
  - r-cachem=1.0.6
  - r-callr=3.7.0
  - r-car=3.0_12
  - r-cardata=3.0_5
  - r-caret=6.0_90
  - r-catools=1.18.2
  - r-cellranger=1.1.0
  - r-checkmate=2.0.0
  - r-class=7.3_20
  - r-cli=3.1.1
  - r-clipr=0.7.1
  - r-cluster=2.1.2
  - r-codetools=0.2_18
  - r-colorspace=2.0_2
  - r-commonmark=1.7
  - r-conquer=1.2.1
  - r-corrplot=0.92
  - r-covr=3.5.1
  - r-cowplot=1.1.1
  - r-cpp11=0.4.2
  - r-crayon=1.4.2
  - r-credentials=1.3.2
  - r-crosstalk=1.2.0
  - r-curl=4.3.2
  - r-data.table=1.14.2
  - r-dbi=1.1.2
  - r-dbplyr=2.1.1
  - r-deoptimr=1.0_10
  - r-desc=1.4.0
  - r-devtools=2.4.3
  - r-diffobj=0.3.5
  - r-digest=0.6.29
  - r-doparallel=1.0.16
  - r-downloader=0.4
  - r-dplyr=1.0.7
  - r-dt=0.20
  - r-dtplyr=1.2.1
  - r-dynamictreecut=1.63_1
  - r-e1071=1.7_9
  - r-ellipsis=0.3.2
  - r-evaluate=0.14
  - r-exactranktests=0.8_34
  - r-fansi=1.0.2
  - r-farver=2.1.0
  - r-fastcluster=1.2.3
  - r-fastmap=1.1.0
  - r-fastmatch=1.1_3
  - r-filelock=1.0.2
  - r-fit.models=0.64
  - r-fontawesome=0.2.2
  - r-forcats=0.5.1
  - r-foreach=1.5.2
  - r-foreign=0.8_82
  - r-formatr=1.11
  - r-formula=1.2_4
  - r-fs=1.5.2
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-future=1.23.0
  - r-future.apply=1.8.1
  - r-gargle=1.2.0
  - r-gdtools=0.2.3
  - r-generics=0.1.2
  - r-gert=1.5.0
  - r-ggforce=0.3.3
  - r-ggfun=0.0.5
  - r-ggplot2=3.3.5
  - r-ggplotify=0.1.0
  - r-ggpubr=0.4.0
  - r-ggraph=2.0.5
  - r-ggrepel=0.9.1
  - r-ggsci=2.9
  - r-ggsignif=0.6.3
  - r-ggtext=0.1.1
  - r-gh=1.3.0
  - r-git2r=0.29.0
  - r-gitcreds=0.1.1
  - r-globals=0.14.0
  - r-glue=1.6.1
  - r-googledrive=2.0.0
  - r-googlesheets4=1.0.0
  - r-gower=1.0.0
  - r-gplots=3.1.1
  - r-graphlayouts=0.8.0
  - r-gridbase=0.4_7
  - r-gridextra=2.3
  - r-gridgraphics=0.5_1
  - r-gridtext=0.1.4
  - r-gtable=0.3.0
  - r-gtools=3.9.2
  - r-haven=2.4.3
  - r-highr=0.9
  - r-hmisc=4.6_0
  - r-hms=1.1.1
  - r-htmltable=2.4.0
  - r-htmltools=0.5.2
  - r-htmlwidgets=1.5.4
  - r-httpuv=1.6.5
  - r-httr=1.4.2
  - r-hwriter=1.3.2
  - r-ids=1.0.1
  - r-igraph=1.2.11
  - r-ini=0.3.1
  - r-ipred=0.9_12
  - r-isoband=0.2.5
  - r-iterators=1.0.14
  - r-jpeg=0.1_9
  - r-jquerylib=0.1.4
  - r-jsonlite=1.7.3
  - r-kernsmooth=2.23_20
  - r-km.ci=0.5_2
  - r-kmsurv=0.1_5
  - r-knitr=1.37
  - r-labeling=0.4.2
  - r-lambda.r=1.2.4
  - r-later=1.2.0
  - r-lattice=0.20_45
  - r-latticeextra=0.6_29
  - r-lava=1.6.10
  - r-lazyeval=0.2.2
  - r-lifecycle=1.0.1
  - r-listenv=0.8.0
  - r-lme4=1.1_27.1
  - r-locfit=1.5_9.4
  - r-lubridate=1.8.0
  - r-magrittr=2.0.2
  - r-maptools=1.1_2
  - r-markdown=1.1
  - r-mass=7.3_55
  - r-matrix=1.4_0
  - r-matrixmodels=0.5_0
  - r-matrixstats=0.61.0
  - r-maxstat=0.7_25
  - r-memoise=2.0.1
  - r-mgcv=1.8_38
  - r-mime=0.12
  - r-minqa=1.2.4
  - r-modelmetrics=1.2.2.2
  - r-modelr=0.1.8
  - r-munsell=0.5.0
  - r-mvtnorm=1.1_3
  - r-nlme=3.1_155
  - r-nloptr=1.2.2.3
  - r-nnet=7.3_17
  - r-numderiv=2016.8_1.1
  - r-openssl=1.4.6
  - r-openxlsx=4.2.5
  - r-parallelly=1.30.0
  - r-patchwork=1.1.1
  - r-pbkrtest=0.5.1
  - r-pcapp=1.9_74
  - r-pheatmap=1.0.12
  - r-pillar=1.7.0
  - r-pkgbuild=1.3.1
  - r-pkgconfig=2.0.3
  - r-pkgload=1.2.4
  - r-plogr=0.2.0
  - r-plyr=1.8.6
  - r-png=0.1_7
  - r-polyclip=1.10_0
  - r-polynom=1.4_0
  - r-praise=1.0.0
  - r-prettyunits=1.1.1
  - r-proc=1.18.0
  - r-processx=3.5.2
  - r-prodlim=2019.11.13
  - r-progress=1.2.2
  - r-progressr=0.10.0
  - r-promises=1.2.0.1
  - r-proxy=0.4_26
  - r-ps=1.6.0
  - r-purrr=0.3.4
  - r-quantreg=5.88
  - r-r6=2.5.1
  - r-rappdirs=0.3.3
  - r-rcmdcheck=1.4.0
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.8
  - r-rcpparmadillo=0.10.8.1.0
  - r-rcppeigen=0.3.3.9.1
  - r-rcurl=1.98_1.5
  - r-readr=2.1.2
  - r-readxl=1.3.1
  - r-recipes=0.1.17
  - r-rematch=1.0.1
  - r-rematch2=2.1.2
  - r-remotes=2.4.2
  - r-reprex=2.0.1
  - r-reshape2=1.4.4
  - r-restfulr=0.0.13
  - r-rex=1.2.1
  - r-rio=0.5.29
  - r-rjson=0.2.21
  - r-rlang=0.4.12
  - r-rmarkdown=2.11
  - r-robust=0.7_0
  - r-robustbase=0.93_9
  - r-roxygen2=7.1.2
  - r-rpart=4.1.16
  - r-rprojroot=2.0.2
  - r-rrcov=1.6_1
  - r-rsqlite=2.2.8
  - r-rstatix=0.7.0
  - r-rstudioapi=0.13
  - r-rvcheck=0.1.8
  - r-rversions=2.1.1
  - r-rvest=1.0.2
  - r-sass=0.4.0
  - r-scales=1.1.1
  - r-scatterpie=0.1.6
  - r-selectr=0.4_2
  - r-sessioninfo=1.2.2
  - r-shadowtext=0.1.1
  - r-shiny=1.7.1
  - r-snow=0.4_4
  - r-sourcetools=0.1.7
  - r-sp=1.4_6
  - r-sparsem=1.81
  - r-squarem=2021.1
  - r-statmod=1.4.36
  - r-stringi=1.7.6
  - r-stringr=1.4.0
  - r-survival=3.2_13
  - r-survminer=0.4.9
  - r-survmisc=0.5.5
  - r-svglite=2.1.0
  - r-sys=3.4
  - r-systemfonts=1.0.3
  - r-testthat=3.1.2
  - r-tibble=3.1.6
  - r-tidygraph=1.2.0
  - r-tidyr=1.2.0
  - r-tidyselect=1.1.1
  - r-tidytree=0.3.7
  - r-tidyverse=1.3.1
  - r-timedate=3043.102
  - r-tinytex=0.36
  - r-treemap=2.4_3
  - r-tweenr=1.0.2
  - r-tzdb=0.2.0
  - r-usethis=2.1.5
  - r-utf8=1.2.2
  - r-uuid=1.0_3
  - r-vctrs=0.3.8
  - r-viridis=0.6.2
  - r-viridislite=0.4.0
  - r-vroom=1.5.7
  - r-waldo=0.3.1
  - r-wgcna=1.69
  - r-whisker=0.4
  - r-withr=2.4.3
  - r-xfun=0.29
  - r-xml=3.99_0.8
  - r-xml2=1.3.3
  - r-xopen=1.0.0
  - r-xtable=1.8_4
  - r-yaml=2.2.2
  - r-yulab.utils=0.0.4
  - r-zip=2.2.0
  - r-zoo=1.8_9
  - readline=8.1
  - rhash=1.4.1
  - samtools=1.14
  - screed=1.0.5
  - sed=4.8
  - setuptools=60.7.1
  - six=1.16.0
  - sqlite=3.37.0
  - sra-tools=2.11.0
  - sysroot_linux-64=2.12
  - t_coffee=11.0.8
  - tabixpp=1.1.0
  - tk=8.6.11
  - tktable=2.10
  - ucsc-facount=377
  - unicodedata2=14.0.0
  - vcflib=1.0.2
  - vcftools=0.1.16
  - vt=2015.11.10
  - wget=1.20.3
  - wheel=0.37.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.2
