channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - automake==1.16.5
  - awscli==1.26.0
  - bcftools==1.16
  - bedtools==2.30.0
  - bioconductor-annotationdbi==1.56.1
  - bioconductor-annotationforge==1.36.0
  - bioconductor-biocparallel==1.28.0
  - bioconductor-biomart==2.50.0
  - bioconductor-clusterprofiler==4.2.0
  - bioconductor-deseq2==1.34.0
  - bioconductor-dexseq==1.40.0
  - bioconductor-enrichplot==1.14.1
  - bioconductor-genefilter==1.76.0
  - bioconductor-go.db==3.14.0
  - bioconductor-impute==1.68.0
  - bioconductor-preprocesscore==1.56.0
  - bioconductor-rhtslib==1.26.0
  - bioconductor-rrvgo==1.6.0
  - bioconductor-rsamtools==2.10.0
  - bioconductor-tcgabiolinks==2.22.1
  - bioconductor-tcgabiolinksgui.data==1.14.1
  - bioconductor-tcgautils==1.14.0
  - bzip2==1.0.8
  - cgpbigwig==1.6.0
  - cmake==3.21.3
  - curl==7.86.0
  - datamash==1.7
  - dos2unix==7.4.1
  - entrez-direct==16.2
  - gcc_linux-64==9.4.0
  - gfortran_linux-64==9.4.0
  - ghostscript==9.54.0
  - glib==2.70.2
  - gxx_linux-64==9.4.0
  - htseq==1.99.2
  - htslib==1.16
  - indexed_bzip2==1.6.0
  - java-jdk==8.0.112
  - khmer==3.0.0a3
  - libcurl==7.86.0
  - libdeflate==1.14
  - libglib==2.70.2
  - libzlib==1.2.13
  - make==4.3
  - nlopt==2.7.1
  - pbzip2==1.1.13
  - perl==5.32.1
  - perl-app-cpanminus==1.7045
  - perl-bio-eutilities==1.75
  - perl-bio-samtools==1.43
  - perl-bioperl==1.7.8
  - perl-compress-raw-zlib==2.202
  - perl-db-file==1.855
  - perl-dbi==1.642
  - perl-libwww-perl==6.68
  - perl-libxml-perl==0.08
  - perl-list-moreutils==0.428
  - perl-try-tiny==0.30
  - perl-xml-parser==2.44_01
  - pkg-config==0.29.2
  - r-argparser==0.7.1
  - r-ashr==2.2_47
  - r-base==4.1.2
  - r-biocmanager==1.30.16
  - r-codetools==0.2_18
  - r-curl==4.3.3
  - r-data.table==1.14.2
  - r-dendextend==1.16.0
  - r-devtools==2.4.3
  - r-dplyr==1.1.2
  - r-ellipse==0.4.5
  - r-ggplot2==3.3.5
  - r-ggpubr==0.4.0
  - r-ggridges==0.5.3
  - r-gplots==3.1.1
  - r-gtools==3.9.2.2
  - r-pheatmap==1.0.12
  - r-r.utils==2.11.0
  - r-rcolorbrewer==1.1_2
  - r-rcurl==1.98_1.12
  - r-reshape2==1.4.4
  - r-survminer==0.4.9
  - r-svglite==2.1.0
  - r-tidyverse==1.3.1
  - r-treemap==2.4_3
  - r-wgcna==1.69
  - samtools==1.16.1
  - sra-tools==2.11.0
  - ucsc-bigwiginfo==466
  - ucsc-facount==377
  - vcflib==1.0.3
  - vcftools==0.1.16
  - vt==2015.11.10
  - wget==1.20.3
  - wiggletools==1.2.11
  - zlib==1.2.13
