name: bbmap
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex==0.1
  - _openmp_mutex==4.5
  - alsa-lib==1.2.10
  - bbmap==39.01
  - bzip2==1.0.8
  - c-ares==1.23.0
  - cairo==1.18.0
  - expat==2.5.0
  - font-ttf-dejavu-sans-mono==2.37
  - font-ttf-inconsolata==3.000
  - font-ttf-source-code-pro==2.038
  - font-ttf-ubuntu==0.83
  - fontconfig==2.14.2
  - fonts-conda-ecosystem==1
  - fonts-conda-forge==1
  - freetype==2.12.1
  - gettext==0.21.1
  - giflib==5.2.1
  - graphite2==1.3.14
  - harfbuzz==8.3.0
  - htslib==1.18
  - icu==73.2
  - keyutils==1.6.1
  - krb5==1.21.2
  - lcms2==2.16
  - lerc==4.0.0
  - libcups==2.3.3
  - libcurl==8.5.0
  - libdeflate==1.19
  - libedit==3.1.20221030
  - libev==4.33
  - libexpat==2.5.0
  - libffi==3.4.4
  - libgcc-ng==13.2.0
  - libglib==2.78.3
  - libgomp==13.2.0
  - libiconv==1.17
  - libjpeg-turbo==3.0.0
  - libnghttp2==1.58.0
  - libpng==1.6.39
  - libssh2==1.11.0
  - libstdcxx-ng==13.2.0
  - libtiff==4.6.0
  - libuuid==2.38.1
  - libwebp-base==1.3.2
  - libxcb==1.15
  - libzlib==1.2.13
  - ncurses==6.4
  - openjdk==21.0.1
  - openssl==3.2.0
  - pbzip2==1.1.13
  - pcre2==10.42
  - pixman==0.42.2
  - pthread-stubs==0.4
  - samtools==1.18
  - xorg-fixesproto==5.0
  - xorg-inputproto==2.3.2
  - xorg-kbproto==1.0.7
  - xorg-libice==1.1.1
  - xorg-libsm==1.2.4
  - xorg-libx11==1.8.7
  - xorg-libxau==1.0.11
  - xorg-libxdmcp==1.1.3
  - xorg-libxext==1.3.4
  - xorg-libxfixes==5.0.3
  - xorg-libxi==1.7.10
  - xorg-libxrender==0.9.11
  - xorg-libxt==1.3.0
  - xorg-libxtst==1.2.3
  - xorg-recordproto==1.14.2
  - xorg-renderproto==0.11.1
  - xorg-xextproto==7.3.0
  - xorg-xproto==7.0.31
  - xz==5.4.5
  - zlib==1.2.13
  - zstd==1.5.5
