name: bbtools
channels:
  - iuc
  - conda-forge
  - bioconda
  - main
  - defaults
  - r
  - anaconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bbmap=38.93
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - htslib=1.14
  - krb5=1.19.2
  - libcurl=7.80.0
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnghttp2=1.43.0
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libzlib=1.2.11
  - ncurses=6.2
  - openjdk=10.0.2
  - openssl=1.1.1l
  - pbzip2=1.1.13
  - samtools=1.14
  - tk=8.6.11
  - xz=5.2.5
  - zlib=1.2.11
