name: bcheck
channels:
  - iuc
  - conda-forge
  - bioconda
  - main
  - defaults
  - r
  - anaconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2021.7.5
  - certifi=2020.6.20
  - infernal=1.1.4
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - ncurses=6.2
  - pip=19.3.1
  - python=2.7.18
  - python_abi=2.7
  - readline=8.1
  - rnabob=2.2.1
  - setuptools=44.0.0
  - sqlite=3.36.0
  - tk=8.6.11
  - wheel=0.37.0
  - zlib=1.2.11
