name: blast
channels:
  - iuc
  - conda-forge
  - bioconda
  - main
  - defaults
  - r
  - anaconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blast=2.12.0
  - bzip2=1.0.8
  - c-ares=1.17.2
  - ca-certificates=2021.5.30
  - curl=7.79.1
  - entrez-direct=15.6
  - krb5=1.19.2
  - libcurl=7.79.1
  - libedit=3.1.20191231
  - libev=4.33
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnghttp2=1.43.0
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libzlib=1.2.11
  - ncurses=6.2
  - openssl=3.0.0
  - pcre=8.45
  - perl=5.26.2
  - perl-archive-tar=2.32
  - perl-carp=1.38
  - perl-common-sense=3.74
  - perl-compress-raw-bzip2=2.087
  - perl-compress-raw-zlib=2.087
  - perl-exporter=5.72
  - perl-exporter-tiny=1.002001
  - perl-extutils-makemaker=7.36
  - perl-io-compress=2.087
  - perl-io-zlib=1.10
  - perl-json=4.02
  - perl-json-xs=2.34
  - perl-list-moreutils=0.428
  - perl-list-moreutils-xs=0.428
  - perl-pathtools=3.75
  - perl-scalar-list-utils=1.52
  - perl-types-serialiser=1.0
  - perl-xsloader=0.24
  - tk=8.6.11
  - zlib=1.2.11
