name: bwa
channels:
  - conda-forge
  - bioconda
  - main
  - defaults
  - r
  - anaconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bwa=0.7.17
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libzlib=1.2.11
  - perl=5.32.1
  - zlib=1.2.11
