name: bwameth
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex==0.1
  - _openmp_mutex==4.5
  - bwa==0.7.17
  - bwa-mem2==2.2.1
  - bwameth==0.2.2
  - bzip2==1.0.8
  - c-ares==1.17.2
  - htslib==1.13
  - keyutils==1.6.1
  - krb5==1.19.2
  - ld_impl_linux-64==2.36.1
  - libcurl==7.79.1
  - libdeflate==1.7
  - libedit==3.1.20191231
  - libev==4.33
  - libffi==3.4.2
  - libgcc-ng==11.2.0
  - libgomp==11.2.0
  - libnghttp2==1.43.0
  - libnsl==2.0.0
  - libssh2==1.10.0
  - libstdcxx-ng==11.2.0
  - libzlib==1.2.11
  - ncurses==6.2
  - openssl==1.1.1l
  - perl==5.32.1
  - pip==21.3.1
  - python==3.9.7
  - python_abi==3.9
  - readline==8.1
  - samtools==1.13
  - setuptools==58.2.0
  - sqlite==3.36.0
  - tk==8.6.11
  - toolshed==0.4.6
  - tzdata==2021c
  - wheel==0.37.0
  - xz==5.2.5
  - zlib==1.2.11
