name: clust
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - charset-normalizer=3.1.0
  - clust=1.18.0
  - contourpy=1.1.0
  - cycler=0.11.0
  - fonttools=4.40.0
  - freetype=2.12.1
  - idna=3.4
  - joblib=1.2.0
  - kiwisolver=1.4.4
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libdeflate=1.18
  - libexpat=2.5.0
  - libffi=3.4.4
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libgomp=13.1.0
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libnsl=2.0.0
  - libopenblas=0.3.23
  - libpng=1.6.39
  - libsqlite=3.42.0
  - libstdcxx-ng=13.1.0
  - libtiff=4.5.0
  - libuuid=2.38.1
  - libwebp-base=1.3.0
  - libxcb=1.15
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - matplotlib-base=3.7.1
  - munkres=1.1.4
  - ncurses=6.4
  - numpy=1.24.3
  - openjpeg=2.5.0
  - openssl=3.1.1
  - packaging=23.1
  - pandas=2.0.2
  - pillow=9.5.0
  - pip=23.1.2
  - platformdirs=3.5.3
  - pooch=1.7.0
  - portalocker=2.7.0
  - pthread-stubs=0.4
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.11.4
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2023.3
  - readline=8.2
  - requests=2.31.0
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - setuptools=67.8.0
  - six=1.16.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - typing-extensions=4.6.3
  - typing_extensions=4.6.3
  - tzdata=2023c
  - urllib3=2.0.3
  - wheel=0.40.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5
