name: cutadapt
channels:
  - conda-forge
  - bioconda
  - main
  - defaults
  - r
  - anaconda
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - cutadapt=2.10
  - dnaio=0.4.2
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openssl=1.1.1h
  - pigz=2.3.4
  - pip=20.2.4
  - python=3.8.5
  - python_abi=3.8
  - readline=8.0
  - setuptools=49.6.0
  - sqlite=3.33.0
  - tk=8.6.10
  - tzdata=2020d
  - wheel=0.35.1
  - xopen=0.9.0
  - xz=5.2.5
  - zlib=1.2.11
