name: danpos
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex==0.1
  - _openmp_mutex==4.5
  - _r-mutex==1.0.1
  - argparse==1.4.0
  - backports==1.0
  - backports.zoneinfo==0.2.1
  - binutils_impl_linux-64==2.40
  - bwidget==1.9.14
  - bzip2==1.0.8
  - c-ares==1.21.0
  - cairo==1.16.0
  - cffi==1.14.6
  - curl==7.87.0
  - expat==2.5.0
  - font-ttf-dejavu-sans-mono==2.37
  - font-ttf-inconsolata==3.000
  - font-ttf-source-code-pro==2.038
  - font-ttf-ubuntu==0.83
  - fontconfig==2.14.2
  - fonts-conda-ecosystem==1
  - fonts-conda-forge==1
  - freetype==2.12.1
  - fribidi==1.0.10
  - gcc_impl_linux-64==13.2.0
  - gettext==0.21.1
  - gfortran_impl_linux-64==13.2.0
  - graphite2==1.3.13
  - gsl==2.7
  - gxx_impl_linux-64==13.2.0
  - harfbuzz==6.0.0
  - htslib==1.17
  - icu==70.1
  - importlib_resources==5.4.0
  - jinja2==3.0.3
  - jpeg==9e
  - kernel-headers_linux-64==2.6.32
  - keyutils==1.6.1
  - krb5==1.19.3
  - ld_impl_linux-64==2.40
  - lerc==4.0.0
  - libblas==3.9.0
  - libcblas==3.9.0
  - libcurl==7.87.0
  - libdeflate==1.13
  - libedit==3.1.20191231
  - libev==4.33
  - libexpat==2.5.0
  - libffi==3.4.2
  - libgcc-devel_linux-64==13.2.0
  - libgcc-ng==13.2.0
  - libgfortran-ng==13.2.0
  - libgfortran5==13.2.0
  - libglib==2.78.0
  - libgomp==13.2.0
  - libiconv==1.17
  - liblapack==3.9.0
  - libnghttp2==1.51.0
  - libnsl==2.0.1
  - libopenblas==0.3.24
  - libpng==1.6.39
  - libsanitizer==13.2.0
  - libsqlite==3.44.0
  - libssh2==1.10.0
  - libstdcxx-devel_linux-64==13.2.0
  - libstdcxx-ng==13.2.0
  - libtiff==4.4.0
  - libuuid==2.38.1
  - libwebp-base==1.3.2
  - libxcb==1.13
  - libxml2==2.10.3
  - libzlib==1.2.13
  - make==4.3
  - markupsafe==2.0.1
  - mysql-connector-c==6.1.11
  - ncurses==6.4
  - numpy==1.19.5
  - openssl==1.1.1w
  - pango==1.50.14
  - pcre2==10.40
  - pip==21.3.1
  - pixman==0.42.2
  - pthread-stubs==0.4
  - pycparser==2.21
  - pysam==0.21.0
  - python==3.6.15
  - python_abi==3.6
  - pytz==2023.3.post1
  - r-base>=4
  - readline==8.2
  - rpy2==3.4.5
  - samtools==1.18
  - scipy==1.5.3
  - sed==4.8
  - setuptools==58.0.4
  - simplegeneric==0.8.1
  - sqlite==3.44.0
  - sysroot_linux-64==2.12
  - tk==8.6.13
  - tktable==2.10
  - tzdata==2023c
  - tzlocal==3.0
  - ucsc-bedgraphtobigwig==445
  - ucsc-bigwigtobedgraph==377
  - ucsc-wigtobigwig==447
  - wheel==0.37.1
  - xorg-kbproto==1.0.7
  - xorg-libice==1.0.10
  - xorg-libsm==1.2.3
  - xorg-libx11==1.8.4
  - xorg-libxau==1.0.11
  - xorg-libxdmcp==1.1.3
  - xorg-libxext==1.3.4
  - xorg-libxrender==0.9.10
  - xorg-libxt==1.3.0
  - xorg-renderproto==0.11.1
  - xorg-xextproto==7.3.0
  - xorg-xproto==7.0.31
  - xz==5.2.6
  - zipp==3.6.0
  - zlib==1.2.13
  - zstd==1.5.5
