channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - argparse==1.4.0
  - numpy==1.19.5
  - pysam==0.21.0
  - r-base==4.1.3
  - rpy2==3.4.5
  - samtools==1.18
  - scipy==1.5.3
  - wiggletools==1.2.11
