name: diego
channels:
  - conda-forge
  - bioconda
  - main
  - defaults
  - r
  - anaconda
dependencies:
  - _libgcc_mutex=0.1
  - bedtools=2.29.2
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - cycler=0.10.0
  - diego=0.1.2
  - freetype=2.10.4
  - htslib=1.11
  - jpeg=9d
  - kiwisolver=1.3.1
  - krb5=1.17.1
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.71.1
  - libdeflate=1.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - liblapack=3.9.0
  - libnghttp2=1.41.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libwebp-base=1.1.0
  - lz4-c=1.9.2
  - matplotlib-base=3.3.2
  - ncurses=6.2
  - numpy=1.19.2
  - olefile=0.46
  - openssl=1.1.1h
  - perl=5.30.3
  - pillow=8.0.1
  - pip=20.2.4
  - pyparsing=2.4.7
  - python=3.9.0
  - python-dateutil=2.8.1
  - python_abi=3.9
  - readline=8.0
  - samtools=1.11
  - scipy=1.5.3
  - setuptools=50.3.0
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - tornado=6.1
  - tzdata=2020d
  - wheel=0.35.1
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
