name: dupsifter
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex==0.1
  - _openmp_mutex==4.5
  - bzip2==1.0.8
  - c-ares==1.24.0
  - dupsifter==1.3.0.20241113
  - keyutils==1.6.1
  - krb5==1.20.1
  - libcurl==8.9.1
  - libdeflate==1.20
  - libedit==3.1.20230828
  - libev==4.33
  - libgcc==14.2.0
  - libgcc-ng==14.2.0
  - libgomp==14.2.0
  - libnghttp2==1.58.0
  - libssh2==1.11.0
  - libstdcxx-ng==13.2.0
  - libzlib==1.2.13
  - ncurses==6.4
  - openssl==3.4.0
  - pthread-stubs==0.4
  - xz==5.4.5
  - zlib==1.2.13
  - zstd==1.5.5
