name: fastqc
channels:
  - conda-forge
  - bioconda
  - main
  - defaults
  - r
  - anaconda
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - fastqc=0.11.9
  - font-ttf-dejavu-sans-mono=2.37
  - fontconfig=2.13.1
  - freetype=2.10.4
  - icu=67.1
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libiconv=1.16
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libuuid=2.32.1
  - libxml2=2.9.10
  - ncurses=6.2
  - openjdk=10.0.2
  - openssl=1.1.1h
  - perl=5.30.3
  - pip=20.2.4
  - python=3.9.0
  - python_abi=3.9
  - readline=8.0
  - setuptools=50.3.0
  - sqlite=3.33.0
  - tk=8.6.10
  - tzdata=2020d
  - wheel=0.35.1
  - xz=5.2.5
  - zlib=1.2.11
