name: fgbio
channels:
  - conda-forge
  - bioconda
  - main
  - defaults
  - r
  - anaconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.0
  - ca-certificates=2022.2.1
  - cairo=1.16.0
  - certifi=2021.10.8
  - fgbio=1.5.1
  - fontconfig=2.13.1
  - freetype=2.11.0
  - fribidi=1.0.10
  - glib=2.69.1
  - graphite2=1.3.14
  - harfbuzz=2.8.1
  - icu=58.2
  - jpeg=9d
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc=7.2.0
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libwebp-base=1.2.2
  - libxcb=1.14
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - ncurses=6.2
  - openjdk=10.0.2
  - openssl=1.1.1m
  - pango=1.45.3
  - pcre=8.45
  - pip=21.1.1
  - pixman=0.40.0
  - python=3.9.2
  - python_abi=3.9
  - r=3.2.2
  - r-base=3.2.2
  - r-boot=1.3_17
  - r-class=7.3_14
  - r-cluster=2.0.3
  - r-codetools=0.2_14
  - r-colorspace=1.2_6
  - r-dichromat=2.0_0
  - r-digest=0.6.9
  - r-foreign=0.8_66
  - r-ggplot2=2.1.0
  - r-gtable=0.1.2
  - r-kernsmooth=2.23_15
  - r-labeling=0.3
  - r-lattice=0.20_33
  - r-magrittr=1.5
  - r-mass=7.3_45
  - r-matrix=1.2_2
  - r-mgcv=1.8_9
  - r-munsell=0.4.2
  - r-nlme=3.1_122
  - r-nnet=7.3_11
  - r-plyr=1.8.3
  - r-rcolorbrewer=1.1_2
  - r-rcpp=0.12.2
  - r-recommended=3.2.2
  - r-reshape2=1.4.1
  - r-rpart=4.1_10
  - r-scales=0.3.0
  - r-spatial=7.3_11
  - r-stringi=1.0_1
  - r-stringr=1.0.0
  - r-survival=2.38_3
  - readline=8.1
  - setuptools=49.6.0
  - sqlite=3.35.5
  - tk=8.6.10
  - tzdata=2021a
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
