name: freebayes
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - bzip2=1.0.8
  - curl=7.71.1
  - freebayes=1.3.2
  - htslib=1.9
  - krb5=1.18.2
  - ld_impl_linux-64=2.33.1
  - libcurl=7.71.1
  - libdeflate=1.2
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libzlib=1.2.11
  - ncurses=6.2
  - openssl=1.1.1h
  - parallel=20160622
  - perl=5.26.2
  - perl-threaded=5.26.0
  - pip=20.3.1
  - python=3.7.9
  - python_abi=3.7
  - readline=8.0
  - setuptools=51.0.0
  - sqlite=3.33.0
  - tk=8.6.10
  - tzdata=2020d
  - wheel=0.35.1
  - xz=5.2.5
  - zlib=1.2.11
