name: freebayes
channels:
  - conda-forge
  - bioconda
  - main
  - defaults
  - r
  - anaconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bc=1.07.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - freebayes=1.3.5
  - htslib=1.14
  - krb5=1.19.2
  - ld_impl_linux-64=2.36.1
  - libcurl=7.81.0
  - libdeflate=1.9
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnghttp2=1.46.0
  - libnsl=2.0.0
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libzlib=1.2.11
  - ncurses=6.2
  - openssl=1.1.1l
  - parallel=20211222
  - perl=5.32.1
  - pip=22.0.3
  - python=3.8.12
  - python_abi=3.8
  - readline=8.1
  - samtools=1.14
  - setuptools=60.7.1
  - sqlite=3.37.0
  - tabixpp=1.1.0
  - tk=8.6.11
  - vcflib=1.0.2
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
