name: genrich
channels:
  - conda-forge
  - bioconda
  - main
  - defaults
  - r
  - anaconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - genrich=0.6.1
  - libgcc-ng=12.2.0
  - libgomp=12.2.0
  - libzlib=1.2.13
  - zlib=1.2.13
