name: homer
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex==0.1
  - _openmp_mutex==4.5
  - gettext==0.21.1
  - homer==4.11
  - libgcc-ng==13.2.0
  - libgomp==13.2.0
  - libidn2==2.3.7
  - libstdcxx-ng==13.2.0
  - libunistring==0.9.10
  - libxcrypt==4.4.36
  - libzlib==1.2.13
  - openssl==3.2.1
  - perl==5.32.1
  - unzip==6.0
  - wget==1.20.3
  - zlib==1.2.13
