name: idr
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex==0.1
  - _openmp_mutex==4.5
  - alsa-lib==1.2.7.2
  - attr==2.5.1
  - brotli==1.0.9
  - brotli-bin==1.0.9
  - bzip2==1.0.8
  - cycler==0.11.0
  - dbus==1.13.6
  - expat==2.4.8
  - fftw==3.3.10
  - font-ttf-dejavu-sans-mono==2.37
  - font-ttf-inconsolata==3.000
  - font-ttf-source-code-pro==2.038
  - font-ttf-ubuntu==0.83
  - fontconfig==2.14.0
  - fonts-conda-ecosystem==1
  - fonts-conda-forge==1
  - fonttools==4.37.1
  - freetype==2.12.1
  - gettext==0.19.8.1
  - glib==2.72.1
  - glib-tools==2.72.1
  - gst-plugins-base==1.20.3
  - gstreamer==1.20.3
  - icu==70.1
  - idr==2.0.4.2
  - jack==1.9.18
  - jpeg==9e
  - keyutils==1.6.1
  - kiwisolver==1.4.4
  - krb5==1.19.3
  - lcms2==2.12
  - ld_impl_linux-64==2.36.1
  - lerc==4.0.0
  - libblas==3.9.0
  - libbrotlicommon==1.0.9
  - libbrotlidec==1.0.9
  - libbrotlienc==1.0.9
  - libcap==2.65
  - libcblas==3.9.0
  - libclang==14.0.6
  - libclang13==14.0.6
  - libcups==2.3.3
  - libdb==6.2.32
  - libdeflate==1.14
  - libedit==3.1.20191231
  - libevent==2.1.10
  - libffi==3.4.2
  - libflac==1.3.4
  - libgcc-ng==12.1.0
  - libgfortran-ng==12.1.0
  - libgfortran5==12.1.0
  - libglib==2.72.1
  - libgomp==12.1.0
  - libiconv==1.16
  - liblapack==3.9.0
  - libllvm14==14.0.6
  - libnsl==2.0.0
  - libogg==1.3.4
  - libopenblas==0.3.21
  - libopus==1.3.1
  - libpng==1.6.37
  - libpq==14.5
  - libsndfile==1.0.31
  - libsqlite==3.39.3
  - libstdcxx-ng==12.1.0
  - libtiff==4.4.0
  - libtool==2.4.6
  - libudev1==249
  - libuuid==2.32.1
  - libvorbis==1.3.7
  - libwebp-base==1.2.4
  - libxcb==1.13
  - libxkbcommon==1.0.3
  - libxml2==2.9.14
  - libzlib==1.2.12
  - matplotlib==3.5.3
  - matplotlib-base==3.5.3
  - munkres==1.1.4
  - mysql-common==8.0.30
  - mysql-libs==8.0.30
  - ncurses==6.3
  - nspr==4.32
  - nss==3.78
  - numpy==1.23.3
  - openjpeg==2.5.0
  - openssl==1.1.1q
  - packaging==21.3
  - pcre==8.45
  - pillow==9.2.0
  - pip==22.2.2
  - ply==3.11
  - portaudio==19.6.0
  - pthread-stubs==0.4
  - pulseaudio==14.0
  - pyparsing==3.0.9
  - pyqt==5.15.7
  - pyqt5-sip==12.11.0
  - python==3.9.13
  - python-dateutil==2.8.2
  - python_abi==3.9
  - qt-main==5.15.6
  - readline==8.1.2
  - scipy==1.9.1
  - setuptools==65.3.0
  - sip==6.6.2
  - six==1.16.0
  - sqlite==3.39.3
  - tk==8.6.12
  - toml==0.10.2
  - tornado==6.2
  - tzdata==2022c
  - unicodedata2==14.0.0
  - wheel==0.37.1
  - xcb-util==0.4.0
  - xcb-util-image==0.4.0
  - xcb-util-keysyms==0.4.0
  - xcb-util-renderutil==0.3.9
  - xcb-util-wm==0.4.1
  - xorg-libxau==1.0.9
  - xorg-libxdmcp==1.1.3
  - xz==5.2.6
  - zstd==1.5.2
