name: igv
channels:
  - conda-forge
  - bioconda
  - main
  - defaults
  - r
  - anaconda
dependencies:
  - _libgcc_mutex=0.1
  - alsa-lib=1.2.3
  - ca-certificates=2021.7.5
  - cairo=1.16.0
  - certifi=2021.5.30
  - fontconfig=2.13.1
  - freetype=2.10.4
  - giflib=5.2.1
  - glib=2.66.1
  - graphite2=1.3.13
  - harfbuzz=2.7.2
  - icu=67.1
  - igv=2.11.1
  - jpeg=9d
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libiconv=1.16
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - ncurses=6.2
  - openjdk=11.0.8
  - openssl=1.1.1l
  - pcre=8.44
  - pip=20.2.4
  - pixman=0.38.0
  - pthread-stubs=0.4
  - python=3.9.0
  - python_abi=3.9
  - readline=8.0
  - setuptools=50.3.0
  - sqlite=3.33.0
  - tk=8.6.10
  - tzdata=2020d
  - wheel=0.35.1
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
