name: infernal
channels:
  - conda-forge
  - bioconda
  - main
  - defaults
  - r
  - anaconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - infernal=1.1.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
