name: intervene
channels:
  - conda-forge
  - bioconda
  - main
  - defaults
  - r
  - anaconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - bedtools=2.30.0
  - binutils_impl_linux-64=2.36.1
  - binutils_linux-64=2.36
  - bwidget=1.9.14
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - cairo=1.14.12
  - certifi=2016.9.26
  - curl=7.69.1
  - cycler=0.11.0
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gcc_impl_linux-64=7.5.0
  - gcc_linux-64=7.5.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=7.5.0
  - gfortran_linux-64=7.5.0
  - glib=2.70.2
  - glib-tools=2.70.2
  - graphite2=1.3.13
  - gsl=2.4
  - gxx_impl_linux-64=7.5.0
  - gxx_linux-64=7.5.0
  - harfbuzz=2.4.0
  - icu=58.2
  - intervene=0.6.5
  - jpeg=9e
  - kernel-headers_linux-64=2.6.32
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - ld_impl_linux-64=2.36.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.69.1
  - libdeflate=1.0
  - libedit=3.1.20191231
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.70.2
  - libgomp=11.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libnsl=2.0.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.12
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - make=4.3
  - matplotlib-base=2.2.4
  - ncurses=6.3
  - numpy=1.19.5
  - openssl=1.1.1l
  - pandas=1.1.5
  - pango=1.45.3
  - patsy=0.5.2
  - pcre=8.45
  - pip=20.0.2
  - pixman=0.40.0
  - pthread-stubs=0.4
  - pybedtools=0.7.10
  - pyparsing=3.0.7
  - pysam=0.15.3
  - python=3.6.15
  - python-dateutil=2.8.2
  - python_abi=3.6
  - pytz=2021.3
  - r-assertthat=0.2.1
  - r-base=3.6.1
  - r-cairo=1.5_10
  - r-cli=1.1.0
  - r-colorspace=1.4_1
  - r-corrplot=0.84
  - r-crayon=1.3.4
  - r-digest=0.6.18
  - r-fansi=0.4.0
  - r-ggplot2=3.1.1
  - r-glue=1.3.1
  - r-gridextra=2.3
  - r-gtable=0.3.0
  - r-labeling=0.4.2
  - r-lattice=0.20_38
  - r-lazyeval=0.2.2
  - r-magrittr=1.5
  - r-mass=7.3_51.3
  - r-matrix=1.2_17
  - r-mgcv=1.8_28
  - r-munsell=0.5.0
  - r-nlme=3.1_139
  - r-pillar=1.3.1
  - r-pkgconfig=2.0.3
  - r-plyr=1.8.6
  - r-r6=2.4.0
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.1
  - r-reshape2=1.4.4
  - r-rlang=0.3.4
  - r-scales=1.0.0
  - r-stringi=1.4.3
  - r-stringr=1.4.0
  - r-tibble=2.1.1
  - r-upsetr=1.4.0
  - r-utf8=1.1.4
  - r-viridislite=0.4.0
  - r-withr=2.1.2
  - readline=8.1
  - scipy=1.5.3
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - setuptools=49.6.0
  - six=1.16.0
  - sqlite=3.37.0
  - statsmodels=0.9.0
  - sysroot_linux-64=2.12
  - tk=8.6.11
  - tktable=2.10
  - tornado=6.1
  - wheel=0.37.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
