name: intervene
channels:
  - conda-forge
  - bioconda
  - main
  - defaults
  - r
  - anaconda
dependencies:
  - _libgcc_mutex=0.1
  - _r-mutex=1.0.1
  - bedtools=2.29.2
  - binutils_impl_linux-64=2.33.1
  - binutils_linux-64=2.33.1
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.11.8
  - cairo=1.16.0
  - certifi=2020.11.8
  - curl=7.71.1
  - cycler=0.10.0
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - gfortran_impl_linux-64=7.3.0
  - gfortran_linux-64=7.3.0
  - glib=2.66.1
  - graphite2=1.3.13
  - gsl=2.6
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - harfbuzz=2.7.2
  - icu=67.1
  - intervene=0.6.5
  - jpeg=9d
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.71.1
  - libdeflate=1.0
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libnghttp2=1.41.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - make=4.3
  - matplotlib-base=3.3.3
  - ncurses=6.2
  - numpy=1.19.4
  - olefile=0.46
  - openssl=1.1.1h
  - pandas=1.1.4
  - pango=1.42.4
  - patsy=0.5.1
  - pcre=8.44
  - pcre2=10.35
  - pillow=8.0.1
  - pip=20.2.4
  - pixman=0.38.0
  - pthread-stubs=0.4
  - pybedtools=0.8.1
  - pyparsing=2.4.7
  - pysam=0.15.3
  - python=3.7.9
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2020.4
  - r-assertthat=0.2.1
  - r-backports=1.2.0
  - r-base=4.0.3
  - r-brio=1.1.0
  - r-cairo=1.5_12.2
  - r-callr=3.5.1
  - r-cli=2.2.0
  - r-colorspace=2.0_0
  - r-corrplot=0.84
  - r-crayon=1.3.4
  - r-desc=1.2.0
  - r-diffobj=0.3.2
  - r-digest=0.6.27
  - r-ellipsis=0.3.1
  - r-evaluate=0.14
  - r-fansi=0.4.1
  - r-farver=2.0.3
  - r-ggplot2=3.3.2
  - r-glue=1.4.2
  - r-gridextra=2.3
  - r-gtable=0.3.0
  - r-isoband=0.2.2
  - r-jsonlite=1.7.1
  - r-labeling=0.4.2
  - r-lattice=0.20_41
  - r-lifecycle=0.2.0
  - r-magrittr=2.0.1
  - r-mass=7.3_53
  - r-matrix=1.2_18
  - r-mgcv=1.8_33
  - r-munsell=0.5.0
  - r-nlme=3.1_150
  - r-pillar=1.4.7
  - r-pkgbuild=1.1.0
  - r-pkgconfig=2.0.3
  - r-pkgload=1.1.0
  - r-plyr=1.8.6
  - r-praise=1.0.0
  - r-prettyunits=1.1.1
  - r-processx=3.4.4
  - r-ps=1.4.0
  - r-r6=2.5.0
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.5
  - r-rematch2=2.1.2
  - r-rlang=0.4.8
  - r-rprojroot=2.0.2
  - r-rstudioapi=0.13
  - r-scales=1.1.1
  - r-testthat=3.0.0
  - r-tibble=3.0.4
  - r-upsetr=1.4.0
  - r-utf8=1.1.4
  - r-vctrs=0.3.5
  - r-viridislite=0.3.0
  - r-waldo=0.2.3
  - r-withr=2.3.0
  - r-zeallot=0.1.0
  - readline=8.0
  - scipy=1.5.3
  - seaborn=0.11.0
  - seaborn-base=0.11.0
  - sed=4.8
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.33.0
  - statsmodels=0.12.1
  - tk=8.6.10
  - tktable=2.10
  - tornado=6.1
  - tzdata=2020d
  - wheel=0.35.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
