name: macs
channels:
  - conda-forge
  - bioconda
  - main
  - defaults
  - r
  - anaconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - cairo=1.16.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.94
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gettext=0.19.8.1
  - graphite2=1.3.13
  - harfbuzz=3.3.1
  - icu=69.1
  - jbig=2.1
  - jpeg=9e
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libdeflate=1.8
  - libffi=3.4.2
  - libgcc=7.2.0
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.70.2
  - libgomp=11.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libnsl=2.0.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxml2=2.9.12
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - macs2=2.2.7.1
  - ncurses=6.3
  - numpy=1.22.2
  - openssl=3.0.0
  - pango=1.50.3
  - pcre=8.45
  - pip=22.0.3
  - pixman=0.40.0
  - pthread-stubs=0.4
  - python=3.9.10
  - python_abi=3.9
  - r-base=3.2.2
  - readline=8.1
  - setuptools=60.7.1
  - sqlite=3.37.0
  - tk=8.6.11
  - tzdata=2021e
  - wheel=0.37.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.2
