name: peakachu
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex==0.1
  - _openmp_mutex==4.5
  - _r-mutex==1.0.1
  - backports==1.0
  - backports.zoneinfo==0.2.1
  - bcbio-gff==0.6.6
  - binutils_impl_linux-64==2.36.1
  - binutils_linux-64==2.36
  - bioconductor-annotate==1.70.0
  - bioconductor-annotationdbi==1.54.0
  - bioconductor-biobase==2.52.0
  - bioconductor-biocgenerics==0.38.0
  - bioconductor-biocparallel==1.26.0
  - bioconductor-biostrings==2.60.0
  - bioconductor-delayedarray==0.18.0
  - bioconductor-deseq2==1.32.0
  - bioconductor-edger==3.34.0
  - bioconductor-genefilter==1.74.0
  - bioconductor-geneplotter==1.70.0
  - bioconductor-genomeinfodb==1.28.0
  - bioconductor-genomeinfodbdata==1.2.6
  - bioconductor-genomicranges==1.44.0
  - bioconductor-iranges==2.26.0
  - bioconductor-keggrest==1.32.0
  - bioconductor-limma==3.48.0
  - bioconductor-matrixgenerics==1.4.0
  - bioconductor-s4vectors==0.30.0
  - bioconductor-summarizedexperiment==1.22.0
  - bioconductor-xvector==0.32.0
  - bioconductor-zlibbioc==1.38.0
  - biopython==1.79
  - blockbuster==0.0.1.1
  - bwidget==1.9.14
  - bx-python==0.8.11
  - bzip2==1.0.8
  - c-ares==1.17.2
  - cairo==1.16.0
  - cffi==1.14.6
  - curl==7.79.1
  - cycler==0.10.0
  - font-ttf-dejavu-sans-mono==2.37
  - font-ttf-inconsolata==3.000
  - font-ttf-source-code-pro==2.038
  - font-ttf-ubuntu==0.83
  - fontconfig==2.13.1
  - fonts-conda-ecosystem==1
  - fonts-conda-forge==1
  - freetype==2.10.4
  - fribidi==1.0.10
  - gcc_impl_linux-64==9.4.0
  - gcc_linux-64==9.4.0
  - gettext==0.19.8.1
  - gfortran_impl_linux-64==9.4.0
  - gfortran_linux-64==9.4.0
  - graphite2==1.3.13
  - gsl==2.7
  - gxx_impl_linux-64==9.4.0
  - gxx_linux-64==9.4.0
  - harfbuzz==3.0.0
  - icu==68.1
  - jbig==2.1
  - jinja2==3.0.2
  - jpeg==9d
  - kernel-headers_linux-64==2.6.32
  - keyutils==1.6.1
  - kiwisolver==1.3.2
  - krb5==1.19.2
  - lcms2==2.12
  - ld_impl_linux-64==2.36.1
  - lerc==2.2.1
  - libblas==3.9.0
  - libcblas==3.9.0
  - libcurl==7.79.1
  - libdeflate==1.7
  - libedit==3.1.20191231
  - libev==4.33
  - libffi==3.4.2
  - libgcc-devel_linux-64==9.4.0
  - libgcc-ng==11.2.0
  - libgfortran-ng==11.2.0
  - libgfortran5==11.2.0
  - libglib==2.68.4
  - libgomp==11.2.0
  - libiconv==1.16
  - liblapack==3.9.0
  - libnghttp2==1.43.0
  - libnsl==2.0.0
  - libopenblas==0.3.17
  - libpng==1.6.37
  - libsanitizer==9.4.0
  - libssh2==1.10.0
  - libstdcxx-devel_linux-64==9.4.0
  - libstdcxx-ng==11.2.0
  - libtiff==4.3.0
  - libuuid==2.32.1
  - libwebp-base==1.2.1
  - libxcb==1.13
  - libxml2==2.9.12
  - libzlib==1.2.11
  - lz4-c==1.9.3
  - lzo==2.10
  - make==4.3
  - markupsafe==2.0.1
  - matplotlib-base==3.4.3
  - ncurses==6.2
  - nomkl==1.0
  - numexpr==2.7.3
  - numpy==1.21.2
  - olefile==0.46
  - openjpeg==2.4.0
  - openssl==1.1.1l
  - pandas==1.3.3
  - pango==1.48.10
  - patsy==0.5.2
  - pcre==8.45
  - pcre2==10.37
  - peakachu==0.2.0
  - pillow==8.3.2
  - pip==21.3.1
  - pixman==0.40.0
  - pthread-stubs==0.4
  - pycparser==2.20
  - pyparsing==2.4.7
  - pysam==0.17.0
  - python==3.8.12
  - python-dateutil==2.8.2
  - python-lzo==1.12
  - python_abi==3.8
  - pytz==2021.3
  - r-askpass==1.1
  - r-assertthat==0.2.1
  - r-backports==1.2.1
  - r-base>=4
  - r-bh==1.75.0_0
  - r-bit==4.0.4
  - r-bit64==4.0.5
  - r-bitops==1.0_7
  - r-blob==1.2.2
  - r-brio==1.1.2
  - r-cachem==1.0.6
  - r-callr==3.7.0
  - r-cli==3.0.1
  - r-colorspace==2.0_2
  - r-crayon==1.4.1
  - r-curl==4.3.2
  - r-dbi==1.1.1
  - r-desc==1.4.0
  - r-diffobj==0.3.5
  - r-digest==0.6.28
  - r-ellipsis==0.3.2
  - r-evaluate==0.14
  - r-fansi==0.4.2
  - r-farver==2.1.0
  - r-fastmap==1.1.0
  - r-formatr==1.11
  - r-futile.logger==1.4.3
  - r-futile.options==1.0.1
  - r-ggplot2==3.3.5
  - r-glue==1.4.2
  - r-gtable==0.3.0
  - r-httr==1.4.2
  - r-isoband==0.2.5
  - r-jsonlite==1.7.2
  - r-labeling==0.4.2
  - r-lambda.r==1.2.4
  - r-lattice==0.20_45
  - r-lifecycle==1.0.1
  - r-locfit==1.5_9.4
  - r-magrittr==2.0.1
  - r-mass==7.3_54
  - r-matrix==1.3_4
  - r-matrixstats==0.61.0
  - r-memoise==2.0.0
  - r-mgcv==1.8_38
  - r-mime==0.12
  - r-munsell==0.5.0
  - r-nlme==3.1_153
  - r-openssl==1.4.5
  - r-pillar==1.6.3
  - r-pkgconfig==2.0.3
  - r-pkgload==1.2.3
  - r-plogr==0.2.0
  - r-png==0.1_7
  - r-praise==1.0.0
  - r-processx==3.5.2
  - r-ps==1.6.0
  - r-r6==2.5.1
  - r-rcolorbrewer==1.1_2
  - r-rcpp==1.0.7
  - r-rcpparmadillo==0.10.7.0.0
  - r-rcurl==1.98_1.5
  - r-rematch2==2.1.2
  - r-rlang==0.4.11
  - r-rprojroot==2.0.2
  - r-rsqlite==2.2.8
  - r-rstudioapi==0.13
  - r-scales==1.1.1
  - r-snow==0.4_3
  - r-survival==3.2_13
  - r-sys==3.4
  - r-testthat==3.1.0
  - r-tibble==3.1.5
  - r-utf8==1.2.2
  - r-vctrs==0.3.8
  - r-viridislite==0.4.0
  - r-waldo==0.3.1
  - r-withr==2.4.2
  - r-xml==3.99_0.8
  - r-xtable==1.8_4
  - readline==8.1
  - rpy2==3.4.5
  - scipy==1.7.1
  - sed==4.8
  - setuptools==58.2.0
  - simplegeneric==0.8.1
  - six==1.16.0
  - sqlite==3.36.0
  - statsmodels==0.13.0
  - sysroot_linux-64==2.12
  - tk==8.6.11
  - tktable==2.10
  - tornado==6.1
  - tzdata==2021c
  - tzlocal==3.0
  - wheel==0.37.0
  - xorg-kbproto==1.0.7
  - xorg-libice==1.0.10
  - xorg-libsm==1.2.3
  - xorg-libx11==1.7.2
  - xorg-libxau==1.0.9
  - xorg-libxdmcp==1.1.3
  - xorg-libxext==1.3.4
  - xorg-libxrender==0.9.10
  - xorg-libxt==1.2.1
  - xorg-renderproto==0.11.1
  - xorg-xextproto==7.3.0
  - xorg-xproto==7.0.31
  - xz==5.2.5
  - zlib==1.2.11
  - zstd==1.5.0
