name: salmon
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex==0.1
  - _openmp_mutex==4.5
  - _r-mutex==1.0.1
  - aioeasywebdav==2.4.0
  - aiohttp==3.9.1
  - aiosignal==1.3.1
  - amply==0.1.6
  - appdirs==1.4.4
  - attmap==0.13.2
  - attrs==23.1.0
  - bcrypt==4.1.1
  - binutils_impl_linux-64==2.40
  - boost-cpp==1.78.0
  - boto3==1.34.1
  - botocore==1.34.1
  - brotli-python==1.1.0
  - bwidget==1.9.14
  - bzip2==1.0.8
  - c-ares==1.23.0
  - cachetools==5.3.2
  - cairo==1.16.0
  - cffi==1.16.0
  - charset-normalizer==3.3.2
  - coin-or-cbc==2.10.10
  - coin-or-cgl==0.60.7
  - coin-or-clp==1.17.8
  - coin-or-osi==0.108.8
  - coin-or-utils==2.11.9
  - coincbc==2.10.10
  - colorama==0.4.6
  - configargparse==1.7
  - connection_pool==0.0.3
  - cryptography==41.0.7
  - curl==8.4.0
  - datrie==0.8.2
  - defusedxml==0.7.1
  - docopt==0.6.2
  - docutils==0.20.1
  - dpath==2.1.6
  - dropbox==11.36.2
  - eido==0.2.2
  - exceptiongroup==1.2.0
  - expat==2.5.0
  - filechunkio==1.8
  - font-ttf-dejavu-sans-mono==2.37
  - font-ttf-inconsolata==3.000
  - font-ttf-source-code-pro==2.038
  - font-ttf-ubuntu==0.83
  - fontconfig==2.14.2
  - fonts-conda-ecosystem==1
  - fonts-conda-forge==1
  - freetype==2.12.1
  - fribidi==1.0.10
  - frozenlist==1.4.0
  - ftputil==5.0.4
  - gcc_impl_linux-64==13.2.0
  - gettext==0.21.1
  - gfortran_impl_linux-64==13.2.0
  - gitdb==4.0.11
  - gitpython==3.1.40
  - gmp==6.3.0
  - google-api-core==2.15.0
  - google-api-python-client==2.111.0
  - google-auth==2.25.2
  - google-auth-httplib2==0.2.0
  - google-cloud-core==2.4.1
  - google-cloud-storage==2.14.0
  - google-crc32c==1.5.0
  - google-resumable-media==2.7.0
  - googleapis-common-protos==1.62.0
  - graphite2==1.3.14
  - grpcio==1.60.0
  - gsl==2.7.1
  - gxx_impl_linux-64==13.2.0
  - harfbuzz==6.0.0
  - httplib2==0.22.0
  - humanfriendly==10.0
  - icu==70.1
  - idna==3.6
  - importlib_resources==6.1.1
  - iniconfig==2.0.0
  - jinja2==3.1.2
  - jmespath==1.0.1
  - jsonschema==4.20.0
  - jsonschema-specifications==2023.11.2
  - jupyter_core==5.5.0
  - kernel-headers_linux-64==2.6.32
  - keyutils==1.6.1
  - krb5==1.20.1
  - ld_impl_linux-64==2.40
  - lerc==4.0.0
  - libabseil==20230802.1
  - libblas==3.9.0
  - libcblas==3.9.0
  - libcrc32c==1.1.2
  - libcurl==8.4.0
  - libdeflate==1.18
  - libedit==3.1.20221030
  - libev==4.33
  - libexpat==2.5.0
  - libffi==3.4.4
  - libgcc-devel_linux-64==13.2.0
  - libgcc-ng==13.2.0
  - libgfortran-ng==13.2.0
  - libgfortran5==13.2.0
  - libglib==2.78.1
  - libgomp==13.2.0
  - libgrpc==1.60.0
  - libhwloc==2.9.1
  - libiconv==1.17
  - libjemalloc==5.3.0
  - libjpeg-turbo==2.1.5.1
  - liblapack==3.9.0
  - liblapacke==3.9.0
  - libnghttp2==1.58.0
  - libnsl==2.0.1
  - libopenblas==0.3.25
  - libpng==1.6.39
  - libprotobuf==4.24.4
  - libre2-11==2023.06.02
  - libsanitizer==13.2.0
  - libsodium==1.0.18
  - libsqlite==3.44.2
  - libssh2==1.11.0
  - libstdcxx-devel_linux-64==13.2.0
  - libstdcxx-ng==13.2.0
  - libtiff==4.5.1
  - libuuid==2.38.1
  - libwebp-base==1.3.2
  - libxcb==1.13
  - libxml2==2.10.3
  - libzlib==1.2.13
  - logmuse==0.2.6
  - make==4.3
  - markdown-it-py==3.0.0
  - markupsafe==2.1.3
  - mdurl==0.1.0
  - multidict==6.0.4
  - nbformat==5.9.2
  - ncurses==6.4
  - numpy==1.26.2
  - oauth2client==4.1.3
  - openssl==3.2.0
  - packaging==23.2
  - pandas==2.1.4
  - pandoc==3.1.3
  - pango==1.50.14
  - paramiko==3.3.1
  - pcre2==10.40
  - peppy==0.35.7
  - pip==23.3.1
  - pixman==0.42.2
  - pkgutil-resolve-name==1.3.10
  - plac==1.4.2
  - platformdirs==4.1.0
  - pluggy==1.3.0
  - ply==3.11
  - prettytable==3.9.0
  - protobuf==4.24.4
  - psutil==5.9.5
  - pthread-stubs==0.4
  - pulp==2.7.0
  - pyasn1==0.5.1
  - pyasn1-modules==0.3.0
  - pycparser==2.21
  - pygments==2.17.2
  - pynacl==1.5.0
  - pyopenssl==23.3.0
  - pyparsing==3.1.1
  - pysftp==0.2.9
  - pysocks==1.7.1
  - pytest==7.4.3
  - python==3.12.0
  - python-dateutil==2.8.2
  - python-fastjsonschema==2.19.0
  - python-irodsclient==1.1.9
  - python-tzdata==2023.3
  - python_abi==3.12
  - pytz==2023.3.post1
  - pyu2f==0.1.5
  - pyyaml==6.0.1
  - r-askpass==1.2.0
  - r-assertthat==0.2.1
  - r-backports==1.4.1
  - r-base>=4
  - r-base64enc==0.1_3
  - r-biocmanager==1.30.22
  - r-bit==4.0.5
  - r-bit64==4.0.5
  - r-blob==1.2.4
  - r-broom==1.0.5
  - r-bslib==0.6.1
  - r-cachem==1.0.8
  - r-callr==3.7.3
  - r-cellranger==1.1.0
  - r-cli==3.6.2
  - r-clipr==0.8.0
  - r-colorspace==2.1_0
  - r-conflicted==1.2.0
  - r-cpp11==0.4.7
  - r-crayon==1.5.2
  - r-curl==5.1.0
  - r-data.table==1.14.10
  - r-dbi==1.1.3
  - r-dbplyr==2.4.0
  - r-digest==0.6.33
  - r-dplyr==1.1.4
  - r-dtplyr==1.3.1
  - r-ellipsis==0.3.2
  - r-evaluate==0.23
  - r-fansi==1.0.6
  - r-farver==2.1.1
  - r-fastmap==1.1.1
  - r-fontawesome==0.5.2
  - r-forcats==1.0.0
  - r-fs==1.6.3
  - r-gargle==1.5.2
  - r-generics==0.1.3
  - r-ggplot2==3.4.4
  - r-glue==1.6.2
  - r-googledrive==2.1.1
  - r-googlesheets4==1.1.1
  - r-gtable==0.3.4
  - r-haven==2.5.4
  - r-highr==0.10
  - r-hms==1.1.3
  - r-htmltools==0.5.7
  - r-httr==1.4.7
  - r-ids==1.0.1
  - r-isoband==0.2.7
  - r-jquerylib==0.1.4
  - r-jsonlite==1.8.8
  - r-knitr==1.45
  - r-labeling==0.4.3
  - r-lattice==0.22_5
  - r-lifecycle==1.0.4
  - r-lubridate==1.9.3
  - r-magrittr==2.0.3
  - r-mass==7.3_60
  - r-matrix==1.6_4
  - r-memoise==2.0.1
  - r-mgcv==1.9_0
  - r-mime==0.12
  - r-modelr==0.1.11
  - r-munsell==0.5.0
  - r-nlme==3.1_164
  - r-openssl==2.1.1
  - r-pillar==1.9.0
  - r-pkgconfig==2.0.3
  - r-prettyunits==1.2.0
  - r-processx==3.8.3
  - r-progress==1.2.3
  - r-ps==1.7.5
  - r-purrr==1.0.2
  - r-r6==2.5.1
  - r-ragg==1.2.5
  - r-rappdirs==0.3.3
  - r-rcolorbrewer==1.1_3
  - r-rcpp==1.0.11
  - r-readr==2.1.4
  - r-readxl==1.4.3
  - r-rematch==2.0.0
  - r-rematch2==2.1.2
  - r-reprex==2.0.2
  - r-rlang==1.1.2
  - r-rmarkdown==2.25
  - r-rstudioapi==0.15.0
  - r-rvest==1.0.3
  - r-sass==0.4.8
  - r-scales==1.3.0
  - r-selectr==0.4_2
  - r-stringi==1.7.12
  - r-stringr==1.5.1
  - r-sys==3.4.2
  - r-systemfonts==1.0.5
  - r-textshaping==0.3.6
  - r-tibble==3.2.1
  - r-tidyr==1.3.0
  - r-tidyselect==1.2.0
  - r-tidyverse==2.0.0
  - r-timechange==0.2.0
  - r-tinytex==0.49
  - r-tzdb==0.4.0
  - r-utf8==1.2.4
  - r-uuid==1.1_1
  - r-vctrs==0.6.5
  - r-viridislite==0.4.2
  - r-vroom==1.6.5
  - r-withr==2.5.2
  - r-writexls==6.4.0
  - r-xfun==0.41
  - r-xml2==1.3.3
  - r-yaml==2.3.8
  - re2==2023.06.02
  - readline==8.2
  - referencing==0.32.0
  - requests==2.31.0
  - reretry==0.11.8
  - rich==13.7.0
  - rpds-py==0.13.2
  - rsa==4.9
  - s3transfer==0.9.0
  - salmon==1.10.2
  - sed==4.8
  - setuptools==68.2.2
  - setuptools-scm==8.0.4
  - six==1.16.0
  - slacker==0.14.0
  - smart_open==6.4.0
  - smmap==5.0.0
  - snakemake==7.32.4
  - snakemake-minimal==7.32.4
  - stone==3.3.1
  - stopit==1.1.2
  - sysroot_linux-64==2.12
  - tabulate==0.9.0
  - tbb==2021.9.0
  - throttler==1.2.2
  - tk==8.6.13
  - tktable==2.10
  - tomli==2.0.1
  - toposort==1.10
  - traitlets==5.14.0
  - typing-extensions==4.9.0
  - typing_extensions==4.9.0
  - tzdata==2023c
  - ubiquerg==0.6.3
  - uritemplate==4.1.1
  - urllib3==1.26.18
  - veracitools==0.1.3
  - wcwidth==0.2.12
  - wheel==0.42.0
  - wrapt==1.16.0
  - xorg-kbproto==1.0.7
  - xorg-libice==1.0.10
  - xorg-libsm==1.2.3
  - xorg-libx11==1.8.4
  - xorg-libxau==1.0.11
  - xorg-libxdmcp==1.1.3
  - xorg-libxext==1.3.4
  - xorg-libxrender==0.9.10
  - xorg-libxt==1.3.0
  - xorg-renderproto==0.11.1
  - xorg-xextproto==7.3.0
  - xorg-xproto==7.0.31
  - xz==5.4.5
  - yaml==0.2.5
  - yarl==1.9.3
  - yte==1.5.4
  - zipp==3.17.0
  - zlib==1.2.13
  - zstd==1.5.5
