channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - docopt==0.6.2
  - pandas==2.1.4
  - r-base==4.2.3
  - r-biocmanager==1.30.22
  - r-scales==1.3.0
  - r-tidyverse==2.0.0
  - r-writexls==6.4.0
  - salmon==1.10.3
  - snakemake==7.32.4
