name: seacr
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - binutils_impl_linux-64=2.40
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.19.1
  - cairo=1.16.0
  - curl=8.2.1
  - expat=2.5.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gcc_impl_linux-64=13.1.0
  - gettext=0.21.1
  - gfortran_impl_linux-64=13.1.0
  - graphite2=1.3.14
  - gsl=2.7.1
  - gxx_impl_linux-64=13.1.0
  - harfbuzz=7.3.0
  - icu=72.1
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - krb5=1.21.2
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libcurl=8.2.1
  - libdeflate=1.18
  - libedit=3.1.20221030
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.4
  - libgcc-devel_linux-64=13.1.0
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libglib=2.76.4
  - libgomp=13.1.0
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libnghttp2=1.52.0
  - libopenblas=0.3.23
  - libpng=1.6.39
  - libsanitizer=13.1.0
  - libssh2=1.11.0
  - libstdcxx-devel_linux-64=13.1.0
  - libstdcxx-ng=13.1.0
  - libtiff=4.5.1
  - libuuid=2.38.1
  - libwebp-base=1.3.1
  - libxcb=1.15
  - libxml2=2.11.5
  - libzlib=1.2.13
  - make=4.3
  - ncurses=6.4
  - openssl=3.1.2
  - pango=1.50.14
  - pcre2=10.40
  - pixman=0.40.0
  - pthread-stubs=0.4
  - r-base>=4
  - readline=8.2
  - seacr=1.3
  - sed=4.8
  - sysroot_linux-64=2.12
  - tk=8.6.12
  - tktable=2.10
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.6
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-libxt=1.3.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5
