name: snpeff
channels:
  - conda-forge
  - bioconda
  - main
  - defaults
  - r
  - anaconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - ld_impl_linux-64=2.36.1
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnsl=2.0.0
  - libuuid=2.32.1
  - libzlib=1.2.11
  - ncurses=6.3
  - openjdk=8.0.312
  - openssl=3.0.0
  - perl=5.32.1
  - pip=22.0.3
  - python=3.10.2
  - python_abi=3.10
  - readline=8.1
  - setuptools=60.7.1
  - snpeff=5.0
  - snpsift=4.3.1t
  - sqlite=3.37.0
  - tk=8.6.11
  - tzdata=2021e
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
