name: sortmerna
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex==0.1
  - _openmp_mutex==4.5
  - brotli-python==1.1.0
  - bzip2==1.0.8
  - charset-normalizer==3.3.2
  - idna==3.7
  - jinja2==3.1.4
  - ld_impl_linux-64==2.40
  - libexpat==2.6.2
  - libffi==3.4.4
  - libgcc-ng==13.2.0
  - libgomp==13.2.0
  - libnsl==2.0.1
  - libsqlite==3.46.0
  - libstdcxx-ng==13.2.0
  - libuuid==2.38.1
  - libxcrypt==4.4.36
  - libzlib==1.3.1
  - markupsafe==2.1.5
  - ncurses==6.5
  - openssl==3.3.1
  - pip==24.0
  - pysocks==1.7.1
  - python==3.12.3
  - python_abi==3.12
  - pyyaml==6.0.1
  - readline==8.2
  - requests==2.32.3
  - setuptools==70.0.0
  - sortmerna==4.3.7
  - tk==8.6.13
  - tzdata==2024a
  - urllib3==2.2.1
  - wheel==0.43.0
  - xz==5.4.6
  - yaml==0.2.5
