channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - automake==1.17
  - cmake==4.0.2
  - conda-build==25.4.2
  - gcc_linux-64==11.4.0
  - glib==2.84.2
  - gxx_linux-64==11.4.0
  - jinja2==3.1.6
  - libglib==2.84.2
  - make==4.4.1
  - ninja==1.12.1
  - pkg-config==0.29.2
  - pyyaml==6.0.2
  - requests==2.32.3
