name: starfusion
channels:
  - conda-forge
  - bioconda
  - main
  - defaults
  - r
  - anaconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bbmap=38.93
  - blast=2.12.0
  - bowtie=1.3.1
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.11
  - cryptography=36.0.1
  - curl=7.81.0
  - entrez-direct=16.2
  - gmap=2021.08.25
  - htslib=1.14
  - idna=3.3
  - igv-reports=1.0.4
  - intervaltree=3.0.2
  - krb5=1.19.2
  - ld_impl_linux-64=2.36.1
  - libcurl=7.81.0
  - libdb=6.2.32
  - libdeflate=1.9
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnghttp2=1.46.0
  - libnsl=2.0.0
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libuuid=2.32.1
  - libzlib=1.2.11
  - ncurses=6.2
  - openjdk=11.0.1
  - openssl=1.1.1l
  - pbzip2=1.1.13
  - pcre=8.45
  - perl=5.26.2
  - perl-archive-tar=2.32
  - perl-business-isbn=3.004
  - perl-business-isbn-data=20140910.003
  - perl-carp=1.38
  - perl-carp-assert=0.21
  - perl-common-sense=3.74
  - perl-compress-raw-bzip2=2.087
  - perl-compress-raw-zlib=2.087
  - perl-constant=1.33
  - perl-data-dumper=2.173
  - perl-db-file=1.855
  - perl-encode=2.88
  - perl-exporter=5.72
  - perl-exporter-tiny=1.002001
  - perl-extutils-makemaker=7.36
  - perl-file-path=2.16
  - perl-findbin=1.51
  - perl-getopt-long=2.50
  - perl-io-compress=2.087
  - perl-io-gzip=0.20
  - perl-io-zlib=1.10
  - perl-json=4.02
  - perl-json-xs=2.34
  - perl-list-moreutils=0.428
  - perl-list-moreutils-xs=0.428
  - perl-list-util=1.38
  - perl-mime-base64=3.15
  - perl-parent=0.236
  - perl-pathtools=3.75
  - perl-scalar-list-utils=1.52
  - perl-set-intervaltree=0.12
  - perl-storable=3.15
  - perl-types-serialiser=1.0
  - perl-uri=1.76
  - perl-xsloader=0.24
  - pip=22.0.3
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysam=0.17.0
  - pysocks=1.7.1
  - python=3.9.9
  - python_abi=3.9
  - readline=8.1
  - requests=2.27.1
  - samtools=1.14
  - setuptools=60.7.1
  - sortedcontainers=2.4.0
  - sqlite=3.37.0
  - star=2.7.10a
  - tbb=2020.2
  - tk=8.6.11
  - tzdata=2021e
  - urllib3=1.26.8
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
