name: starfusion
channels:
  - conda-forge
  - bioconda
  - main
  - defaults
  - r
  - anaconda
dependencies:
  - _libgcc_mutex=0.1
  - bbmap=38.87
  - blast=2.9.0
  - boost=1.68.0
  - boost-cpp=1.68.0
  - bowtie=1.3.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2022.6.15
  - certifi=2021.5.30
  - cffi=1.11.5
  - chardet=3.0.4
  - cryptography=3.2.1
  - gmap=2020.10.14
  - gmp=6.2.0
  - gnutls=3.6.13
  - htslib=1.11
  - icu=58.2
  - idna=2.10
  - igv-reports=1.0.1
  - intervaltree=3.0.2
  - krb5=1.17.1
  - ld_impl_linux-64=2.33.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.71.1
  - libdb=6.2.32
  - libdeflate=1.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - liblapack=3.9.0
  - libnghttp2=1.41.0
  - libopenblas=0.3.12
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - nettle=3.4.1
  - numpy=1.19.2
  - openjdk=11.0.1
  - openssl=1.1.1o
  - pbzip2=1.1.13
  - pcre=8.44
  - perl=5.26.2
  - perl-archive-tar=2.32
  - perl-business-isbn=3.004
  - perl-business-isbn-data=20140910.003
  - perl-carp=1.38
  - perl-carp-assert=0.21
  - perl-common-sense=3.74
  - perl-compress-raw-bzip2=2.087
  - perl-compress-raw-zlib=2.087
  - perl-constant=1.33
  - perl-data-dumper=2.173
  - perl-db-file=1.855
  - perl-encode=2.88
  - perl-exporter=5.72
  - perl-exporter-tiny=1.002001
  - perl-extutils-makemaker=7.36
  - perl-file-path=2.16
  - perl-findbin=1.51
  - perl-getopt-long=2.50
  - perl-io-compress=2.087
  - perl-io-gzip=0.20
  - perl-io-zlib=1.10
  - perl-json-xs=4.02
  - perl-list-moreutils=0.428
  - perl-list-moreutils-xs=0.428
  - perl-list-util=1.38
  - perl-mime-base64=3.15
  - perl-parent=0.236
  - perl-pathtools=3.75
  - perl-scalar-list-utils=1.52
  - perl-set-intervaltree=0.12
  - perl-storable=3.15
  - perl-types-serialiser=1.0
  - perl-uri=1.76
  - perl-xsloader=0.24
  - pip=20.2.4
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pysam=0.16.0.1
  - pysocks=1.7.1
  - python=3.6.12
  - python_abi=3.6
  - readline=8.0
  - requests=2.24.0
  - samtools=1.11
  - setuptools=49.6.0
  - six=1.15.0
  - sortedcontainers=2.2.2
  - sqlite=3.33.0
  - star=2.7.10a
  - tbb=2020.2
  - tk=8.6.10
  - tzdata=2020d
  - urllib3=1.25.11
  - wheel=0.35.1
  - xz=5.2.5
  - zlib=1.2.11
