name: umitools
channels:
  - conda-forge
  - bioconda
  - main
  - defaults
  - r
  - anaconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cycler=0.11.0
  - editdistance=0.6.0
  - fonttools=4.30.0
  - freetype=2.10.4
  - giflib=5.2.1
  - jbig=2.1
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.0
  - krb5=1.19.3
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.82.0
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.3.0
  - libuuid=2.32.1
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libzlib=1.2.11
  - lz4-c=1.9.3
  - matplotlib-base=3.5.1
  - munkres=1.1.4
  - ncurses=6.3
  - networkx=2.7.1
  - numpy=1.22.3
  - openjpeg=2.4.0
  - openssl=1.1.1l
  - packaging=21.3
  - pandas=1.4.1
  - pillow=9.0.1
  - pip=22.0.4
  - pthread-stubs=0.4
  - pyparsing=3.0.7
  - pysam=0.18.0
  - python=3.9.10
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2021.3
  - readline=8.1
  - scipy=1.8.0
  - setuptools=60.9.3
  - six=1.16.0
  - sqlite=3.37.1
  - tk=8.6.12
  - tzdata=2022a
  - umitools=0.3.4
  - unicodedata2=14.0.0
  - wheel=0.37.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.2
