name: umitools
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex==0.1
  - _openmp_mutex==4.5
  - brotli==1.1.0
  - brotli-bin==1.1.0
  - brotli-python==1.1.0
  - bzip2==1.0.8
  - c-ares==1.20.1
  - charset-normalizer==3.3.0
  - contourpy==1.1.1
  - cycler==0.12.1
  - fonttools==4.43.1
  - freetype==2.12.1
  - future==0.18.3
  - idna==3.4
  - importlib-resources==6.1.0
  - importlib_resources==6.1.0
  - keyutils==1.6.1
  - kiwisolver==1.4.5
  - krb5==1.21.2
  - lcms2==2.15
  - ld_impl_linux-64==2.40
  - lerc==4.0.0
  - libblas==3.9.0
  - libbrotlicommon==1.1.0
  - libbrotlidec==1.1.0
  - libbrotlienc==1.1.0
  - libcblas==3.9.0
  - libcurl==8.4.0
  - libdeflate==1.18
  - libedit==3.1.20221030
  - libev==4.33
  - libffi==3.4.4
  - libgcc-ng==13.2.0
  - libgfortran-ng==13.2.0
  - libgfortran5==13.2.0
  - libgomp==13.2.0
  - libjpeg-turbo==2.1.5.1
  - liblapack==3.9.0
  - libnghttp2==1.57.0
  - libnsl==2.0.0
  - libopenblas==0.3.24
  - libpng==1.6.39
  - libsqlite==3.43.2
  - libssh2==1.11.0
  - libstdcxx-ng==13.2.0
  - libtiff==4.6.0
  - libuuid==2.38.1
  - libwebp-base==1.3.2
  - libxcb==1.15
  - libzlib==1.2.13
  - matplotlib-base==3.7.3
  - munkres==1.1.4
  - ncurses==6.4
  - numpy==1.24.4
  - openjpeg==2.5.0
  - openssl==3.1.3
  - packaging==23.2
  - pandas==2.0.3
  - pillow==10.0.1
  - pip==23.2.1
  - platformdirs==3.11.0
  - pooch==1.7.0
  - pthread-stubs==0.4
  - pybktree==1.1
  - pyparsing==3.1.1
  - pysam==0.21.0
  - pysocks==1.7.1
  - python==3.8.18
  - python-dateutil==2.8.2
  - python-tzdata==2023.3
  - python_abi==3.8
  - pytz==2023.3.post1
  - readline==8.2
  - regex==2023.10.3
  - requests==2.31.0
  - scipy==1.10.1
  - setuptools==68.2.2
  - six==1.16.0
  - tk==8.6.13
  - typing-extensions==4.8.0
  - typing_extensions==4.8.0
  - umi_tools==1.1.1
  - unicodedata2==15.1.0
  - urllib3==2.0.6
  - wheel==0.41.2
  - xorg-libxau==1.0.11
  - xorg-libxdmcp==1.1.3
  - xz==5.4.2
  - zipp==3.17.0
  - zlib==1.2.13
  - zstd==1.5.5
