name: varscan
channels:
  - conda-forge
  - bioconda
  - main
  - defaults
  - r
  - anaconda
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openjdk=10.0.2
  - openssl=1.1.1h
  - pip=20.2.4
  - python=3.9.0
  - python_abi=3.9
  - readline=8.0
  - setuptools=50.3.0
  - sqlite=3.33.0
  - tk=8.6.10
  - tzdata=2020d
  - varscan=2.4.4
  - wheel=0.35.1
  - xz=5.2.5
  - zlib=1.2.11
